name: build
on:
  push:

jobs:
  build:
    name: Build-${{ matrix.cfg.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cfg:
          - name: Apple
            options: apple
          - name: Banana
            options: banana
          - name: Cherry
            options: cherry

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build ${{ matrix.cfg.name }}
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: badger
          docker-image-tag: ${{ matrix.cfg.options }}
          dockerfile-path: ./Dockerfile.${{ matrix.cfg.options }}

